var DogBreed = [
    {"breed_name":"Affenpinscher"},
    {"breed_name":"Afghan"},
    {"breed_name":"Afghan Hound"},
    {"breed_name":"Airedale"},
    {"breed_name":"Airedale Terrier"},
    {"breed_name":"Akbash"},
    {"breed_name":"Akita"},
    {"breed_name":"Alaskan Klee Kai"},
    {"breed_name":"Alaskan Malamute"},
    {"breed_name":"American Bulldog"},
    {"breed_name":"American Bully"},
    {"breed_name":"American Cocker Spaniel"},
    {"breed_name":"American Eskimo Dog"},
    {"breed_name":"American Foxhound"},
    {"breed_name":"American Hairless Terrier"},
    {"breed_name":"American Pit Bull Terrier"},
    {"breed_name":"American Staffordshire Terrier"},
    {"breed_name":"American Water Spaniel "},
    {"breed_name":"Anatolian Karabash Dog"},
    {"breed_name":"Anatolian Shepherd"},
    {"breed_name":"Appenzell Mountain Dog"},
    {"breed_name":"Argentinian Mastiff"},
    {"breed_name":"Australian Cattle Dog"},
    {"breed_name":"Australian Cattle Dog/Blue Heeler"},
    {"breed_name":"Australian Kelpie"},
    {"breed_name":"Australian Shepherd"},
    {"breed_name":"Australian Terrier"},
    {"breed_name":"Basenji"},
    {"breed_name":"Basset Griffon Vendeen"},
    {"breed_name":"Basset Hound"},
    {"breed_name":"Beagle "},
    {"breed_name":"Bearded Collie"},
    {"breed_name":"Beauceron"},
    {"breed_name":"Bedlington Terrier"},
    {"breed_name":"Belgian Griffon"},
    {"breed_name":"Belgian Malinois"},
    {"breed_name":"Belgian Shepherd "},
    {"breed_name":"Belgian Shepherd Dog Sheepdog"},
    {"breed_name":"Belgian Shepherd Laekenois"},
    {"breed_name":"Belgian Shepherd Malinois"},
    {"breed_name":"Belgian Shepherd Tervuren"},
    {"breed_name":"Belgian Tervuren"},
    {"breed_name":"Bernese Mountain Dog"},
    {"breed_name":"Bichon Frise"},
    {"breed_name":"Biewer"},
    {"breed_name":"Black and Tan Coonhound"},
    {"breed_name":"Black Labrador Retriever"},
    {"breed_name":"Black Mouth Cur"},
    {"breed_name":"Black Russian Terrier"},
    {"breed_name":"Bloodhound"},
    {"breed_name":"Blue Lacy"},
    {"breed_name":"Bluetick Coonhound"},
    {"breed_name":"Bobtail"},
    {"breed_name":"Boerboel Mastiff"},
    {"breed_name":"Bolognese"},
    {"breed_name":"Bordeaux"},
    {"breed_name":"Border Collie"},
    {"breed_name":"Border Terrier"},
    {"breed_name":"Borzoi"},
    {"breed_name":"Boston Terrier"},
    {"breed_name":"Bouvier des Flanders"},
    {"breed_name":"Boxer"},
    {"breed_name":"Boykin Spaniel"},
    {"breed_name":"Brazilian Mastiff"},
    {"breed_name":"Briard"},
    {"breed_name":"Brittany "},
    {"breed_name":"Brussels Griffon"},
    {"breed_name":"Bull Terrier"},
    {"breed_name":"Bulldog"},
    {"breed_name":"Bullmastiff"},
    {"breed_name":"Cairn Terrier"},
    {"breed_name":"Canaan Dog"},
    {"breed_name":"Canarian Molosser"},
    {"breed_name":"Cane Corso Mastiff"},
    {"breed_name":"Cardigan Welsh Corgi"},
    {"breed_name":"Carolina Dog"},
    {"breed_name":"Catahoula Leopard Dog"},
    {"breed_name":"Cattle Dog"},
    {"breed_name":"Caucasian Sheepdog (Caucasian Ovtcharka)"},
    {"breed_name":"Cavalier King Charles Spaniel"},
    {"breed_name":"Chesapeake Bay Retriever"},
    {"breed_name":"Chihuahua"},
    {"breed_name":"Chinese Crested"},
    {"breed_name":"Chinese Crested-Hairless"},
    {"breed_name":"Chinese Crested-Powder Puff"},
    {"breed_name":"Chinese Foo Dog"},
    {"breed_name":"Chinese Shar Pei"},
    {"breed_name":"Chinook"},
    {"breed_name":"Chocolate Labrador Retriever"},
    {"breed_name":"Chow Chow"},
    {"breed_name":"Cirneco dellEtna"},
    {"breed_name":"Clumber Spaniel"},
    {"breed_name":"Cockapoo"},
    {"breed_name":"Cocker Spaniel"},
    {"breed_name":"Collie"},
    {"breed_name":"Coonhound"},
    {"breed_name":"Corgi"},
    {"breed_name":"Coton de Tulear"},
    {"breed_name":"Curly-Coated Retriever"},
    {"breed_name":"Dachshund"},
    {"breed_name":"Dalmatian"},
    {"breed_name":"Dandie Dinmont Terrier"},
    {"breed_name":"Danish Broholmer"},
    {"breed_name":"Deerhound"},
    {"breed_name":"Doberman"},
    {"breed_name":"Doberman Pinscher"},
    {"breed_name":"Dogo Argentino"},
    {"breed_name":"Dogue de Bordeaux"},
    {"breed_name":"Dutch Shepherd"},
    {"breed_name":"Elkhound"},
    {"breed_name":"English Bulldog"},
    {"breed_name":"English Cocker Spaniel"},
    {"breed_name":"English Coonhound"},
    {"breed_name":"English Foxhound"},
    {"breed_name":"English Mastiff"},
    {"breed_name":"English Pointer"},
    {"breed_name":"English Setter"},
    {"breed_name":"English Sheepdog"},
    {"breed_name":"English Shepherd"},
    {"breed_name":"English Springer Spaniel"},
    {"breed_name":"English Toy Spaniel"},
    {"breed_name":"Entlebucher"},
    {"breed_name":"Eskimo Dog"},
    {"breed_name":"Eskimo Spitz"},
    {"breed_name":"Eurasier"},
    {"breed_name":"Feist"},
    {"breed_name":"Field Spaniel"},
    {"breed_name":"Fila Brasileiro"},
    {"breed_name":"Finnish Lapphund"},
    {"breed_name":"Finnish Spitz"},
    {"breed_name":"Flat-Coated Retriever"},
    {"breed_name":"Fox Terrier"},
    {"breed_name":"Foxhound"},
    {"breed_name":"French Brittany"},
    {"breed_name":"French Bulldog"},
    {"breed_name":"French Mastiff"},
    {"breed_name":"Galgo Spanish Greyhound"},
    {"breed_name":"German Pinscher"},
    {"breed_name":"German Shepherd Dog"},
    {"breed_name":"German Shorthaired Pointer"},
    {"breed_name":"German Spitz"},
    {"breed_name":"German Wirehaired Pointer"},
    {"breed_name":"Giant Schnauzer"},
    {"breed_name":"Glen of Imaal Terrier"},
    {"breed_name":"Golden Retriever"},
    {"breed_name":"Goldendoodle"},
    {"breed_name":"Gordon Setter"},
    {"breed_name":"Great Dane"},
    {"breed_name":"Great Pyrenees"},
    {"breed_name":"Greater Swiss Mountain Dog"},
    {"breed_name":"Greyhound"},
    {"breed_name":"Halden Hound (Haldenstrover)"},
    {"breed_name":"Harrier"},
    {"breed_name":"Havanese"},
    {"breed_name":"Hollandse Tulphond"},
    {"breed_name":"Hound"},
    {"breed_name":"Hovawart"},
    {"breed_name":"Husky"},
    {"breed_name":"Ibezian Hound"},
    {"breed_name":"Ibizan Hound"},
    {"breed_name":"Illyrian Sheepdog"},
    {"breed_name":"Irish Setter"},
    {"breed_name":"Irish Terrier"},
    {"breed_name":"Irish Water Spaniel"},
    {"breed_name":"Irish Wolfhound"},
    {"breed_name":"Italian Greyhound"},
    {"breed_name":"Italian Mastiff"},
    {"breed_name":"Italian Spinone"},
    {"breed_name":"Jack Russell Terrier"},
    {"breed_name":"Jack Russell Terrier (Parson Russell Terrier)"},
    {"breed_name":"Japanese Chin"},
    {"breed_name":"Jindo (Korean)"},
    {"breed_name":"Kai Dog"},
    {"breed_name":"Karelian Bear Dog"},
    {"breed_name":"Keeshond"},
    {"breed_name":"Kerry Bule Terrier"},
    {"breed_name":"Kishu"},
    {"breed_name":"Klee Kai"},
    {"breed_name":"Komondor"},
    {"breed_name":"Komondor"},
    {"breed_name":"Kuvasz"},
    {"breed_name":"Kyi Leo"},
    {"breed_name":"Labrador Retriever"},
    {"breed_name":"Lakeland Terrier"},
    {"breed_name":"Lancashire Heeler"},
    {"breed_name":"Leonberger"},
    {"breed_name":"Lhasa Apso"},
    {"breed_name":"Lowchen"},
    {"breed_name":"Maltese"},
    {"breed_name":"Manchester Terrier"},
    {"breed_name":"Maremma Sheepdog"},
    {"breed_name":"Markiesje"},
    {"breed_name":"Mastiff"},
    {"breed_name":"McNab"},
    {"breed_name":"Mexican Hairless"},
    {"breed_name":"Miniature Bull Terrier"},
    {"breed_name":"Miniature Pinscher"},
    {"breed_name":"Miniature Poodle"},
    {"breed_name":"Miniature Schnauzer"},
    {"breed_name":"Mountain Cur"},
    {"breed_name":"Mountain Dog"},
    {"breed_name":"Munsterlander"},
    {"breed_name":"Neapolitan Mastiff"},
    {"breed_name":"New Guinea Singing Dog"},
    {"breed_name":"Newfoundland"},
    {"breed_name":"Newfoundland Dog"},
    {"breed_name":"Norfolk Terrier"},
    {"breed_name":"Norwegian Buhund"},
    {"breed_name":"Norwegian Elkhound"},
    {"breed_name":"Norwegian Lundehund"},
    {"breed_name":"Norwich Terrier"},
    {"breed_name":"Nova Scotia Duck Tolling Retriever"},
    {"breed_name":"Old English Sheepdog"},
    {"breed_name":"OTHER - please specify in notes"},
    {"breed_name":"Otterhound"},
    {"breed_name":"Papillion"},
    {"breed_name":"Parson Russell Terrier"},
    {"breed_name":"Patterdale Terrier (Fell Terrier)"},
    {"breed_name":"Pekingese"},
    {"breed_name":"Pembroke Welsh Corgi"},
    {"breed_name":"Peruvian Inca Orchid"},
    {"breed_name":"Petit Basset Griffon Vendeen"},
    {"breed_name":"Pharaoh Hound"},
    {"breed_name":"Picardy Shepherd"},
    {"breed_name":"Pit Bull Terrier"},
    {"breed_name":"Pitbull"},
    {"breed_name":"Plott Hound"},
    {"breed_name":"Podengo Portugueso"},
    {"breed_name":"Pointer"},
    {"breed_name":"Polish Lowland Sheepdog"},
    {"breed_name":"Pomeranian"},
    {"breed_name":"Poodle (Miniature)"},
    {"breed_name":"Poodle (Standard)"},
    {"breed_name":"Poodle (T-Cup)"},
    {"breed_name":"Poodle (Toy)"},
    {"breed_name":"Poodle (unknown type)"},
    {"breed_name":"Portugese Water Dog"},
    {"breed_name":"Presa Canario"},
    {"breed_name":"Pug"},
    {"breed_name":"Puli"},
    {"breed_name":"Pumi"},
    {"breed_name":"Queensland Heeler"},
    {"breed_name":"Rat Terrier"},
    {"breed_name":"Red Heeler"},
    {"breed_name":"Redbone Coonhound"},
    {"breed_name":"Retriever"},
    {"breed_name":"Rhodesian Ridgeback"},
    {"breed_name":"Rottweiler"},
    {"breed_name":"Russian Wolfhound"},
    {"breed_name":"Saarlooswolfhond"},
    {"breed_name":"Saint Bernard"},
    {"breed_name":"Saluki"},
    {"breed_name":"Saluki Greyhound"},
    {"breed_name":"Samoyed"},
    {"breed_name":"Schiller Hound"},
    {"breed_name":"Schipperke"},
    {"breed_name":"Schnauzer"},
    {"breed_name":"Scottish Deerhound"},
    {"breed_name":"Scottish Terrier"},
    {"breed_name":"Scottish Terrier Scottie"},
    {"breed_name":"Sealyham Terrier"},
    {"breed_name":"Setter"},
    {"breed_name":"Shar Pei"},
    {"breed_name":"Sheep Dog"},
    {"breed_name":"Shepherd"},
    {"breed_name":"Shetland Sheepdog"},
    {"breed_name":"Shetland Sheepdog Sheltie"},
    {"breed_name":"Shiba Inu"},
    {"breed_name":"Shih Tzu"},
    {"breed_name":"Siberian Husky"},
    {"breed_name":"Silken Windhound"},
    {"breed_name":"Silky Terrier"},
    {"breed_name":"Skye Terrier"},
    {"breed_name":"Sloughi"},
    {"breed_name":"Smooth Fox Terrier"},
    {"breed_name":"Soft Coated Wheaten Terrier"},
    {"breed_name":"South Russian Ovcharka"},
    {"breed_name":"Spaniel"},
    {"breed_name":"Spanish Mastiff"},
    {"breed_name":"Spinoni Italiano"},
    {"breed_name":"Spitz"},
    {"breed_name":"Springer Spaniel"},
    {"breed_name":"Staffordshire Bull Terrier"},
    {"breed_name":"Standard Poodle"},
    {"breed_name":"Standard Schnauzer"},
    {"breed_name":"Sussex Spaniel"},
    {"breed_name":"Swedish Vallhund"},
    {"breed_name":"Terrier"},
    {"breed_name":"Thai Ridgeback"},
    {"breed_name":"Tibetan Mastiff"},
    {"breed_name":"Tibetan Spaniel"},
    {"breed_name":"Tibetan Terrier"},
    {"breed_name":"Tosa Inu"},
    {"breed_name":"Toy Fox Terrier"},
    {"breed_name":"Toy Manchester Terrier"},
    {"breed_name":"Toy Poodle"},
    {"breed_name":"Toy Terrier"},
    {"breed_name":"Treeing Walker Coonhound"},
    {"breed_name":"Unknown"},
    {"breed_name":"Vizsla"},
    {"breed_name":"Weimaraner"},
    {"breed_name":"Welsh Corgi"},
    {"breed_name":"Welsh Springer Spaniel "},
    {"breed_name":"Welsh Terrier"},
    {"breed_name":"West Highland White Terrier Westie"},
    {"breed_name":"Westhighland White Terrier"},
    {"breed_name":"Wheaten Terrier"},
    {"breed_name":"Whippet"},
    {"breed_name":"White German Shepherd"},
    {"breed_name":"Wire Fox Terrier"},
    {"breed_name":"Wire-haired Pointing Griffon"},
    {"breed_name":"Wirehaired Fox Terrier"},
    {"breed_name":"Wirehaired Pointing Griffon"},
    {"breed_name":"Wolf Dog"},
    {"breed_name":"Xoloitzcuintle/Mexican Hairless"},
    {"breed_name":"Yellow Labrador Retriever"},
    {"breed_name":"Yorkshire Terrier"},
    {"breed_name":"Yorkshire Terrier Yorkie"}
]


module.exports = DogBreed;
