var DogBreed = [
    {"breed_name": "柴犬"},
    {"breed_name": "串串-小型犬"},
    {"breed_name": "阿拉斯加雪橇犬"},
    {"breed_name": "万能梗"},
    {"breed_name": "苏俄猎狼犬"},
    {"breed_name": "戈登雪达犬"},
    {"breed_name": "蝴蝶犬"},
    {"breed_name": "拉萨犬"},
    {"breed_name": "萨摩耶犬"},
    {"breed_name": "短脚长身梗"},
    {"breed_name": "京巴犬"},
    {"breed_name": "西施犬"},
    {"breed_name": "杰克罗素梗"},
    {"breed_name": "中亚牧羊犬"},
    {"breed_name": "丝毛梗"},
    {"breed_name": "巨型雪纳瑞"},
    {"breed_name": "纽芬兰犬"},
    {"breed_name": "威尔士梗"},
    {"breed_name": "圣伯纳犬"},
    {"breed_name": "苏格兰牧羊犬"},
    {"breed_name": "加纳利"},
    {"breed_name": "银狐犬"},
    {"breed_name": "英国可卡犬"},
    {"breed_name": "松狮犬"},
    {"breed_name": "波利犬"},
    {"breed_name": "荷兰毛狮犬"},
    {"breed_name": "葡萄牙水犬"},
    {"breed_name": "西高地梗"},
    {"breed_name": "迷你贝吉格里芬凡丁犬"},
    {"breed_name": "史宾格猎犬"},
    {"breed_name": "哈士奇"},
    {"breed_name": "比熊犬"},
    {"breed_name": "吉娃娃"},
    {"breed_name": "边境牧羊犬"},
    {"breed_name": "爱尔兰猎狼犬"},
    {"breed_name": "拳师犬"},
    {"breed_name": "金毛犬"},
    {"breed_name": "苏格兰梗"},
    {"breed_name": "波音达犬"},
    {"breed_name": "寻血猎犬"},
    {"breed_name": "泰迪犬"},
    {"breed_name": "贝林顿梗"}
]


module.exports = DogBreed;
