var DogColor = [
    {"name": "Amber"},
    {"name": "Apricot"},
    {"name": "APRICOT AND GRAY"},
    {"name": "APRICOT AND TAN"},
    {"name": "Apricot and White"},
    {"name": "Apricot Fawn"},
    {"name": "Apricot-Red"},
    {"name": "Apricot/Red"},
    {"name": "Apricot/Wht"},
    {"name": "Auburn"},
    {"name": "b"},
    {"name": "B&W"},
    {"name": "Baby Blue Collar"},
    {"name": "Balck"},
    {"name": "Beatifully Black"},
    {"name": "Beaver"},
    {"name": "Beige"},
    {"name": "Beige & Black"},
    {"name": "Beige & White"},
    {"name": "Beige and Brown"},
    {"name": "Beige and White"},
    {"name": "Beige/Black"},
    {"name": "Bi-Color"},
    {"name": "BiColor"},
    {"name": "BIEGE"},
    {"name": "Biscuit"},
    {"name": "Biscuit and White"},
    {"name": "BL BRINDLE"},
    {"name": "Bl Brindle & White"},
    {"name": "BL BRINDLE AND BLACK"},
    {"name": "BL BRINDLE AND BROWN"},
    {"name": "BL BRINDLE AND GRAY"},
    {"name": "BL BRINDLE AND TAN"},
    {"name": "BL BRINDLE AND WHITE"},
    {"name": "Bl brindle/Wht"},
    {"name": "Bl Tick/Red Tick"},
    {"name": "Bl Tick/Tricolor"},
    {"name": "Bl Tick/wht"},
    {"name": "Black"},
    {"name": "Black & Blue Merle"},
    {"name": "Black & Brown"},
    {"name": "Black & Cream"},
    {"name": "Black & Gold"},
    {"name": "Black & Mahogany"},
    {"name": "Black & Red"},
    {"name": "Black & Rust"},
    {"name": "Black & Tan"},
    {"name": "Black & White"},
    {"name": "Black & White & Brown"},
    {"name": "Black and Apricot"},
    {"name": "Black and Beige"},
    {"name": "BLACK AND BL BRINDLE"},
    {"name": "Black and Blonde"},
    {"name": "BLACK AND BLUE"},
    {"name": "BLACK AND BLUE MERLE"},
    {"name": "BLACK AND BR BRINDLE"},
    {"name": "Black and Brown"},
    {"name": "Black and Brown Brindle"},
    {"name": "BLACK AND BUFF"},
    {"name": "Black and Cream"},
    {"name": "Black and Gold"},
    {"name": "Black and Gray"},
    {"name": "Black and Mahogany"},
    {"name": "Black and Red"},
    {"name": "Black and Rust"},
    {"name": "BLACK AND SABLE"},
    {"name": "Black and Silver"},
    {"name": "Black and Tan"},
    {"name": "BLACK AND TORTIE"},
    {"name": "BLACK AND TRICOLOR"},
    {"name": "Black and White"},
    {"name": "Black Brindle"},
    {"name": "Black Brindle & White"},
    {"name": "Black Brown & White"},
    {"name": "Black Fawn & White"},
    {"name": "Black Gold & White"},
    {"name": "Black Gray & White"},
    {"name": "Black Mantle"},
    {"name": "Black Sable"},
    {"name": "Black Sabled Fawn"},
    {"name": "Black Tan & White"},
    {"name": "BLACK TRI"},
    {"name": "Black White"},
    {"name": "Black White & Silver"},
    {"name": "Black White & Tan"},
    {"name": "Black with Brown  Red  Golden  Orange or Chestnut"},
    {"name": "Black with Brown, Red, Golden, Orange or Chestnut"},
    {"name": "Black with Gray or Silver"},
    {"name": "Black with Tan"},
    {"name": "Black with Tan  Yellow or Fawn"},
    {"name": "Black with Tan, Yellow or Fawn"},
    {"name": "Black with White"},
    {"name": "Black with white markings"},
    {"name": "Black witrh White"},
    {"name": "Black, Brown and Orange"},
    {"name": "Black, Brown and Tan"},
    {"name": "Black, Brown and White"},
    {"name": "Black, Brown, and White"},
    {"name": "Black, Gray and Tan"},
    {"name": "Black, Gray and White"},
    {"name": "Black, Red and White"},
    {"name": "Black, Rust and White"},
    {"name": "Black, Tan & White"},
    {"name": "Black, Tan and Silver"},
    {"name": "Black, Tan and White"},
    {"name": "Black, White and Orange"},
    {"name": "Black, White and Red"},
    {"name": "Black,BrownandWhite"},
    {"name": "Black/Brown/White"},
    {"name": "Black/Gray/White"},
    {"name": "black/tan"},
    {"name": "Black/White"},
    {"name": "Black&Cream"},
    {"name": "Black&Gold"},
    {"name": "Black&Mahogany"},
    {"name": "Black&Rust"},
    {"name": "Black&SilverDapple"},
    {"name": "Black&Tan"},
    {"name": "Black&White"},
    {"name": "BlackandBrown"},
    {"name": "BlackandSilver"},
    {"name": "BlackandTan"},
    {"name": "BlackandWhite"},
    {"name": "blackbrown"},
    {"name": "BlackBrown&White"},
    {"name": "BlackGray&White"},
    {"name": "BlackWhite&Tan"},
    {"name": "Blenheim"},
    {"name": "Blk"},
    {"name": "BLK BRINDLE"},
    {"name": "BLK SMOKE"},
    {"name": "BLK SMOKE AND WHITE"},
    {"name": "BLK TIGER"},
    {"name": "BLK TIGER AND BLACK"},
    {"name": "BLK TIGER AND WHITE"},
    {"name": "Blk/Blk"},
    {"name": "Blk/Brindle"},
    {"name": "Blk/Brn"},
    {"name": "Blk/Brown"},
    {"name": "Blk/Grey"},
    {"name": "Blk/Red"},
    {"name": "Blk/Tan"},
    {"name": "BLK/TAN/WHT"},
    {"name": "Blk/Tricolor"},
    {"name": "Blk/Whi"},
    {"name": "Blk/Wht"},
    {"name": "Blond"},
    {"name": "Blonde"},
    {"name": "Blonde And Black"},
    {"name": "Blonde and White"},
    {"name": "Blue"},
    {"name": "Blue & Gold"},
    {"name": "Blue and Black"},
    {"name": "BLUE AND BROWN"},
    {"name": "Blue and Cream"},
    {"name": "Blue and Gold"},
    {"name": "Blue and Tan"},
    {"name": "Blue and White"},
    {"name": "Blue Belton & Tan (Tri-Color)"},
    {"name": "Blue Brindle"},
    {"name": "BLUE CREAM"},
    {"name": "Blue Fawn"},
    {"name": "Blue Fawn Brindle"},
    {"name": "Blue Gray"},
    {"name": "Blue Gray and White"},
    {"name": "Blue Merle"},
    {"name": "BLUE MERLE AND BLACK"},
    {"name": "BLUE MERLE AND BROWN"},
    {"name": "BLUE MERLE AND CREAM"},
    {"name": "BLUE MERLE AND GRAY"},
    {"name": "BLUE MERLE AND TAN"},
    {"name": "BLUE MERLE AND TRICOLOR"},
    {"name": "Blue Merle and White"},
    {"name": "Blue Merle/Brn"},
    {"name": "Blue Mottled"},
    {"name": "Blue Point"},
    {"name": "Blue Speckled"},
    {"name": "BLUE TICK"},
    {"name": "BLUE TICK AND TAN"},
    {"name": "Blue tick/Red"},
    {"name": "BLUE TIGER"},
    {"name": "BLUE TIGER AND WHITE"},
    {"name": "Blue, Cream and White"},
    {"name": "Blue, Gray and White"},
    {"name": "Blue, Silver and Tan"},
    {"name": "Blue, Tan and White"},
    {"name": "Blue/Blk"},
    {"name": "Blue/Silver/Salt & Pepper"},
    {"name": "Blue/Tan"},
    {"name": "Blue/Whi"},
    {"name": "Blue/Wht"},
    {"name": "Blue&Gold"},
    {"name": "BlueMerle"},
    {"name": "Bluetick"},
    {"name": "Bluetick and White"},
    {"name": "Bown"},
    {"name": "BR BRINDLE"},
    {"name": "BR BRINDLE AND BL BRINDLE"},
    {"name": "BR BRINDLE AND BLACK"},
    {"name": "BR BRINDLE AND BROWN"},
    {"name": "BR BRINDLE AND GRAY"},
    {"name": "BR BRINDLE AND TAN"},
    {"name": "BR BRINDLE AND TRICOLOR"},
    {"name": "BR BRINDLE AND WHITE"},
    {"name": "Br Brindle/gray"},
    {"name": "Br Brindle/Tan"},
    {"name": "Br Brindle/Wht"},
    {"name": "Br, Brindle/Wht"},
    {"name": "Br. Brindle/Wht"},
    {"name": "Briddle"},
    {"name": "Bridle & White"},
    {"name": "Brindle"},
    {"name": "Brindle & White"},
    {"name": "Brindle and White"},
    {"name": "Brindle with White"},
    {"name": "Brindle/Whi"},
    {"name": "Brindle/white"},
    {"name": "Brindle&White"},
    {"name": "BRN MERLE"},
    {"name": "BRN MERLE AND BLACK"},
    {"name": "BRN MERLE AND TAN"},
    {"name": "BRN MERLE AND WHITE"},
    {"name": "BRN TIGER"},
    {"name": "BRN TIGER AND BLACK"},
    {"name": "BRN TIGER AND WHITE"},
    {"name": "Brn.Sable/Wht"},
    {"name": "Brn/Blk"},
    {"name": "Brn/Brn"},
    {"name": "Brn/Cream"},
    {"name": "Brn/Tan"},
    {"name": "Brn/Whi"},
    {"name": "Brn/Wht"},
    {"name": "Bronze"},
    {"name": "Brown"},
    {"name": "Brown & Black"},
    {"name": "Brown & Cream"},
    {"name": "Brown & Silver"},
    {"name": "Brown & Tan"},
    {"name": "brown & white"},
    {"name": "BROWN AND BL BRINDLE"},
    {"name": "BROWN AND BLACK"},
    {"name": "Brown and Blonde"},
    {"name": "BROWN AND BLUE"},
    {"name": "BROWN AND BLUE MERLE"},
    {"name": "BROWN AND BR BRINDLE"},
    {"name": "BROWN AND BRN MERLE"},
    {"name": "Brown and Cream"},
    {"name": "BROWN AND FAWN"},
    {"name": "BROWN AND GOLD"},
    {"name": "Brown and Gray"},
    {"name": "Brown And Grey"},
    {"name": "BROWN AND RED"},
    {"name": "Brown and Tan"},
    {"name": "BROWN AND TORTIE"},
    {"name": "BROWN AND TRICOLOR"},
    {"name": "Brown and White"},
    {"name": "Brown Brindle"},
    {"name": "Brown Dapple"},
    {"name": "BROWN SPOTS"},
    {"name": "Brown, Black, and Gray"},
    {"name": "Brown, White and Tan"},
    {"name": "Brown, White, and Tan"},
    {"name": "Brown/Chocolate"},
    {"name": "Brown/Chocolate with Black"},
    {"name": "Brown/Chocolate with Tan"},
    {"name": "Brown/Chocolate with White"},
    {"name": "Brown/tan"},
    {"name": "Brown/White"},
    {"name": "BrownandWhite"},
    {"name": "Brwn"},
    {"name": "Buckskin"},
    {"name": "Buff"},
    {"name": "BUFF AND BROWN"},
    {"name": "BUFF AND GOLD"},
    {"name": "BUFF AND TAN"},
    {"name": "Buff and White"},
    {"name": "Buff with cream"},
    {"name": "Butterscotch"},
    {"name": "Caf"},
    {"name": "Caf? Au Lait"},
    {"name": "Café Au Lait"},
    {"name": "Café Sable"},
    {"name": "Calico"},
    {"name": "CALICO AND WHITE"},
    {"name": "CAMEL"},
    {"name": "Caramel"},
    {"name": "Carmel"},
    {"name": "Carmel/White"},
    {"name": "Champagne"},
    {"name": "Charcoal"},
    {"name": "Charcoal and White"},
    {"name": "Chesnut/Golden"},
    {"name": "Chestnut"},
    {"name": "Chestnut Roan"},
    {"name": "Chestnut/White"},
    {"name": "Chihuahua"},
    {"name": "Chocolate"},
    {"name": "Chocolate & Tan"},
    {"name": "CHOCOLATE AND BLACK"},
    {"name": "CHOCOLATE AND BROWN"},
    {"name": "CHOCOLATE AND CREAM"},
    {"name": "Chocolate and Tan"},
    {"name": "Chocolate and White"},
    {"name": "Chocolate Phantom"},
    {"name": "Chocolate/Red"},
    {"name": "Chocolate/tan"},
    {"name": "ChocolateBrindle"},
    {"name": "Cinnamon"},
    {"name": "Cinnamon and White"},
    {"name": "Copper"},
    {"name": "Copper and White"},
    {"name": "Copper&White"},
    {"name": "CowGirl"},
    {"name": "Cream"},
    {"name": "Cream & White"},
    {"name": "CREAM AND BLACK"},
    {"name": "CREAM AND BR BRINDLE"},
    {"name": "CREAM AND BROWN"},
    {"name": "CREAM AND GOLD"},
    {"name": "Cream and Gray"},
    {"name": "CREAM AND TAN"},
    {"name": "Cream and White"},
    {"name": "Cream/Apricot"},
    {"name": "Cream/Black"},
    {"name": "Cream/Blk"},
    {"name": "Cream/White"},
    {"name": "Cream/Wht"},
    {"name": "Cream&White"},
    {"name": "CREME"},
    {"name": "Dapple"},
    {"name": "Dapple Grey"},
    {"name": "DAPPLE PIE"},
    {"name": "DAPPLE RED"},
    {"name": "Dark Brindle"},
    {"name": "Dark Brown"},
    {"name": "Dark Golden"},
    {"name": "Deadgrass"},
    {"name": "Diluted Tortoiseshell"},
    {"name": "Double Merle"},
    {"name": "Dun"},
    {"name": "FAUN"},
    {"name": "Fawn"},
    {"name": "Fawn (Isabella)"},
    {"name": "Fawn & Black"},
    {"name": "Fawn & White"},
    {"name": "FAWN AND BLACK"},
    {"name": "FAWN AND GRAY"},
    {"name": "FAWN AND TAN"},
    {"name": "Fawn and White"},
    {"name": "FAWN AND Y BRINDLE"},
    {"name": "fawn with black"},
    {"name": "Fawn with black mask"},
    {"name": "Fawn, Black Overlay"},
    {"name": "Fawn(Isabella)"},
    {"name": "Fawn/Blue"},
    {"name": "Fawn/Sable"},
    {"name": "Fawn/tan"},
    {"name": "Fawn&Black"},
    {"name": "Fawn&White"},
    {"name": "Ginger"},
    {"name": "Gold"},
    {"name": "Gold & White"},
    {"name": "GOLD AND BLACK"},
    {"name": "Gold and Brown"},
    {"name": "GOLD AND RED"},
    {"name": "GOLD AND SILVER"},
    {"name": "GOLD AND TRICOLOR"},
    {"name": "Gold and White"},
    {"name": "GOLD AND YELLOW"},
    {"name": "Gold/Whi"},
    {"name": "Gold/Wht"},
    {"name": "Golden"},
    {"name": "Golden Brown"},
    {"name": "Golden Rust"},
    {"name": "Golden/Chestnut"},
    {"name": "Golden/Fawn"},
    {"name": "GoldenRust"},
    {"name": "Grary"},
    {"name": "Gray"},
    {"name": "Gray / Tan"},
    {"name": "Gray & Black"},
    {"name": "Gray & White"},
    {"name": "GRAY AND BL BRINDLE"},
    {"name": "GRAY AND BLACK"},
    {"name": "GRAY AND BLUE"},
    {"name": "GRAY AND BR BRINDLE"},
    {"name": "GRAY AND BROWN"},
    {"name": "GRAY AND CHOCOLATE"},
    {"name": "GRAY AND CREAM"},
    {"name": "Gray and fawn"},
    {"name": "GRAY AND RED"},
    {"name": "GRAY AND SILVER"},
    {"name": "Gray and Tan"},
    {"name": "GRAY AND TRICOLOR"},
    {"name": "Gray and White"},
    {"name": "Gray Brindle"},
    {"name": "GRAY DAPPLE"},
    {"name": "GRAY TIGER"},
    {"name": "GRAY TIGER AND GRAY"},
    {"name": "Gray, Brown and White"},
    {"name": "Gray, Cream and White"},
    {"name": "Gray, Tan and White"},
    {"name": "Gray/Blk"},
    {"name": "Gray/Blue/Silver w/ White"},
    {"name": "gray/silver"},
    {"name": "Gray/Silver/Salt & Pepper with Black"},
    {"name": "Gray/Silver/Salt & Pepper with White"},
    {"name": "Gray/Tan"},
    {"name": "Gray/Wht"},
    {"name": "Gray&White"},
    {"name": "Grey"},
    {"name": "Grey & Brown"},
    {"name": "Grey & White"},
    {"name": "grey and white"},
    {"name": "Grey Tan and White"},
    {"name": "Grey w/ white chest"},
    {"name": "Grey, Cream and White"},
    {"name": "Grey/Cream"},
    {"name": "Grey/Whi"},
    {"name": "Grey/Wht"},
    {"name": "Grizzle"},
    {"name": "Grizzle and Tan"},
    {"name": "Harlequin"},
    {"name": "Hazel"},
    {"name": "Heavy Marked"},
    {"name": "Honey"},
    {"name": "http://www.animalarkshelter.org/animal/AnimalArk.n"},
    {"name": "http://www.animalarkshelter.org/animal/AnimalArk.n"},
    {"name": "http://www.animalarkshelter.org/animal/AnimalArk.n"},
    {"name": "Lavender"},
    {"name": "Lemon"},
    {"name": "Lemon and White"},
    {"name": "LEOPORD"},
    {"name": "Light Brindle"},
    {"name": "Light Brown"},
    {"name": "LIGHT GOLD"},
    {"name": "Light Golden"},
    {"name": "light tan"},
    {"name": "LightGolden"},
    {"name": "Lilac"},
    {"name": "Liver"},
    {"name": "Liver & White"},
    {"name": "LIVER AND TAN"},
    {"name": "Liver and White"},
    {"name": "Liver Roan"},
    {"name": "Liver White"},
    {"name": "Liver with White"},
    {"name": "Liver/Whi"},
    {"name": "Lynx Point"},
    {"name": "Mahogany"},
    {"name": "Mahogany & White"},
    {"name": "Mantle"},
    {"name": "Marble"},
    {"name": "Merle"},
    {"name": "Merle/Tan"},
    {"name": "Merlequin"},
    {"name": "Mis Marked"},
    {"name": "Mocha"},
    {"name": "Multi"},
    {"name": "Neutered"},
    {"name": "Non"},
    {"name": "None"},
    {"name": "Oak"},
    {"name": "Orange"},
    {"name": "Orange & White"},
    {"name": "Orange and Black"},
    {"name": "Orange and White"},
    {"name": "Orange Collar"},
    {"name": "Orange&White"},
    {"name": "OrangeandWhite"},
    {"name": "Other/Not Listed"},
    {"name": "Parti"},
    {"name": "PARTY"},
    {"name": "Pepper"},
    {"name": "Phantom"},
    {"name": "Piebald"},
    {"name": "PIED"},
    {"name": "Pink"},
    {"name": "Purple"},
    {"name": "Re/Blk"},
    {"name": "Red"},
    {"name": "Red & Rust"},
    {"name": "Red & Tan"},
    {"name": "Red & White"},
    {"name": "Red & Wht"},
    {"name": "RED AND BLACK"},
    {"name": "RED AND BR BRINDLE"},
    {"name": "Red and Brown"},
    {"name": "RED AND BUFF"},
    {"name": "Red and Gold"},
    {"name": "RED AND RED MERLE"},
    {"name": "Red and Tan"},
    {"name": "Red and White"},
    {"name": "RED BRINDLE"},
    {"name": "Red Collar"},
    {"name": "Red Dapple"},
    {"name": "Red Fawn"},
    {"name": "RED MEREL"},
    {"name": "Red Merle"},
    {"name": "RED MERLE AND BROWN"},
    {"name": "RED MERLE AND WHITE"},
    {"name": "Red Merle/Wht"},
    {"name": "RED SABLE"},
    {"name": "Red Sesame"},
    {"name": "Red Speckled"},
    {"name": "RED TICK"},
    {"name": "RED TICK AND BROWN"},
    {"name": "RED TICK AND WHITE"},
    {"name": "RED TRI"},
    {"name": "Red Wheaten"},
    {"name": "Red Wheaton"},
    {"name": "Red, Black and Cream"},
    {"name": "Red/Brn"},
    {"name": "Red/Gold/Orange/Chestnut"},
    {"name": "Red/Golden/Gray"},
    {"name": "Red/Golden/Orange/Chestnut with Black"},
    {"name": "Red/Golden/Orange/Chestnut with White"},
    {"name": "Red/Tan"},
    {"name": "Red/White"},
    {"name": "Red/Wht"},
    {"name": "Red&White"},
    {"name": "RedandWhite"},
    {"name": "RedFawn"},
    {"name": "Redish Brown"},
    {"name": "RedMerle"},
    {"name": "Redtick"},
    {"name": "Redtick and White"},
    {"name": "Reverse Brindle"},
    {"name": "Roan"},
    {"name": "Ruby"},
    {"name": "Ruddy"},
    {"name": "Rust"},
    {"name": "Rust and White"},
    {"name": "Sable"},
    {"name": "Sable & White"},
    {"name": "SABLE AND BLACK"},
    {"name": "SABLE AND TAN"},
    {"name": "Sable and White"},
    {"name": "Sable Merle and White"},
    {"name": "Sable/Tan"},
    {"name": "Sable/Wht"},
    {"name": "Sable&White"},
    {"name": "SALT"},
    {"name": "salt & peper"},
    {"name": "Salt & Pepper"},
    {"name": "Salt and Pepper"},
    {"name": "Salt&Pepper"},
    {"name": "SaltandPepper"},
    {"name": "Sandy"},
    {"name": "Seagull"},
    {"name": "Seal"},
    {"name": "Seal and White"},
    {"name": "Seal/Blk"},
    {"name": "Sesame"},
    {"name": "Silver"},
    {"name": "Silver & Tan (Yorkie colors)"},
    {"name": "Silver & White"},
    {"name": "SILVER AND BLACK"},
    {"name": "Silver and Black and Tan"},
    {"name": "SILVER AND GOLD"},
    {"name": "Silver and Gray"},
    {"name": "SILVER AND TAN"},
    {"name": "SILVER AND WHITE"},
    {"name": "Silver Blue"},
    {"name": "Silver Daple"},
    {"name": "Silver Dapple"},
    {"name": "Silver Gold & White"},
    {"name": "Silver Gray"},
    {"name": "Silver Gray & Black"},
    {"name": "Silver/Tan"},
    {"name": "SilverDaple"},
    {"name": "SilverFawn"},
    {"name": "SilverGray"},
    {"name": "SLVR TIGER"},
    {"name": "Smoke"},
    {"name": "Spayed"},
    {"name": "Spotted"},
    {"name": "Steel"},
    {"name": "Striped"},
    {"name": "Tabby"},
    {"name": "Tabby and White"},
    {"name": "Tan"},
    {"name": "Tan / Black"},
    {"name": "Tan / White"},
    {"name": "Tan & Black"},
    {"name": "Tan & Cream"},
    {"name": "Tan & White"},
    {"name": "TAN AND BLACK"},
    {"name": "Tan And Blck"},
    {"name": "TAN AND BROWN"},
    {"name": "TAN AND BUFF"},
    {"name": "TAN AND CHOCOLATE"},
    {"name": "Tan and Cream"},
    {"name": "TAN AND GOLD"},
    {"name": "TAN AND GRAY"},
    {"name": "TAN AND RED"},
    {"name": "TAN AND SILVER"},
    {"name": "TAN AND TRICOLOR"},
    {"name": "Tan and White"},
    {"name": "TAN AND YELLOW"},
    {"name": "Tan Cream And Gray"},
    {"name": "Tan Fawn"},
    {"name": "Tan with Black"},
    {"name": "Tan, Black and White"},
    {"name": "Tan, Cream and White"},
    {"name": "Tan, white"},
    {"name": "Tan/Blk"},
    {"name": "Tan/Brn"},
    {"name": "Tan/Brown"},
    {"name": "Tan/Brown /Black"},
    {"name": "Tan/Cream"},
    {"name": "Tan/fawn"},
    {"name": "Tan/golden/fawn"},
    {"name": "Tan/gray"},
    {"name": "Tan/Sable"},
    {"name": "Tan/Tan"},
    {"name": "Tan/Whi"},
    {"name": "Tan/White"},
    {"name": "Tan/Wht"},
    {"name": "Tan/Yellow/Fawn"},
    {"name": "Tan/Yellow/Fawn w/ Black"},
    {"name": "Tan/Yellow/Fawn w/ White"},
    {"name": "Tan/Yellow/Fawn with Black"},
    {"name": "Tan/Yellow/Fawn with White"},
    {"name": "Taupe"},
    {"name": "Tawny"},
    {"name": "Tick"},
    {"name": "Ticked"},
    {"name": "Tiger"},
    {"name": "Tortie"},
    {"name": "Tortoiseshell"},
    {"name": "Tri"},
    {"name": "Tri Color"},
    {"name": "Tri colored"},
    {"name": "TRI MERLE"},
    {"name": "TRI RED"},
    {"name": "Tri-Color"},
    {"name": "Tri-Colored"},
    {"name": "TRICOLOR"},
    {"name": "Tricolor (Tan/Brown & Black & White)"},
    {"name": "TRICOLOR AND BLACK"},
    {"name": "TRICOLOR AND BLUE MERLE"},
    {"name": "TRICOLOR AND BROWN"},
    {"name": "TRICOLOR AND CREAM"},
    {"name": "TRICOLOR AND TAN"},
    {"name": "TRICOLOR AND WHITE"},
    {"name": "Tricolor/Blk"},
    {"name": "Tricolored"},
    {"name": "Unknown"},
    {"name": "Unspecified"},
    {"name": "Wheat"},
    {"name": "Wheaten"},
    {"name": "Wheaten (Buff)"},
    {"name": "Wheaten(Buff)"},
    {"name": "Wheaton"},
    {"name": "Whi/Choc"},
    {"name": "while"},
    {"name": "White"},
    {"name": "White & Black"},
    {"name": "White & Brindle"},
    {"name": "White & Brown"},
    {"name": "White & Chocolate"},
    {"name": "White & Gold"},
    {"name": "White & Gray"},
    {"name": "White & Tan"},
    {"name": "WHITE AND APRICOT"},
    {"name": "White And Beige"},
    {"name": "WHITE AND BL BRINDLE"},
    {"name": "White and Black"},
    {"name": "WHITE AND BLUE"},
    {"name": "WHITE AND BLUE MERLE"},
    {"name": "White and Blue Merle and Tan"},
    {"name": "WHITE AND BR BRINDLE"},
    {"name": "White and Brindle"},
    {"name": "WHITE AND BRN MERLE"},
    {"name": "White and Brown"},
    {"name": "WHITE AND BUFF"},
    {"name": "WHITE AND CHOCOLATE"},
    {"name": "WHITE AND CREAM"},
    {"name": "WHITE AND FAWN"},
    {"name": "WHITE AND GOLD"},
    {"name": "WHITE AND GRAY"},
    {"name": "WHITE AND LIVER"},
    {"name": "WHITE AND ORANGE"},
    {"name": "White and peach"},
    {"name": "WHITE AND RED"},
    {"name": "WHITE AND RED MERLE"},
    {"name": "white and tan"},
    {"name": "WHITE AND TORTIE"},
    {"name": "WHITE AND TRICOLOR"},
    {"name": "WHITE AND YELLOW"},
    {"name": "White Brindle"},
    {"name": "White Grey"},
    {"name": "White Merle"},
    {"name": "WHITE ON CHEST"},
    {"name": "white w/ black"},
    {"name": "White w/ Red/Golden/Orange"},
    {"name": "White w/ Tan/Yellow/Fawn"},
    {"name": "White with Black"},
    {"name": "White with black spots and brindle"},
    {"name": "White with brown"},
    {"name": "White with Brown or Chocolate"},
    {"name": "White with Gray or Silver"},
    {"name": "white with grey"},
    {"name": "White with Red  Golden  Orange or Chestnut"},
    {"name": "White with Red, Golden, Orange or Chestnut"},
    {"name": "White with Tan"},
    {"name": "White with Tan  Yellow or Fawn"},
    {"name": "White with Tan, Yellow or Fawn"},
    {"name": "White, Chocolate & Tan"},
    {"name": "white/black"},
    {"name": "White/Brn"},
    {"name": "White/Brown"},
    {"name": "White/Cream"},
    {"name": "White/golden"},
    {"name": "White/tan"},
    {"name": "White/yellow"},
    {"name": "White&Black"},
    {"name": "White&Cream"},
    {"name": "White&Sable"},
    {"name": "White&Tan"},
    {"name": "WhiteBlack&Tan"},
    {"name": "Wht"},
    {"name": "Wht/Bl Merle"},
    {"name": "Wht/Blk"},
    {"name": "Wht/Br Brindle"},
    {"name": "Wht/Brn"},
    {"name": "Wht/Cream"},
    {"name": "Wht/Liver"},
    {"name": "Wht/Red"},
    {"name": "Wht/Tan"},
    {"name": "Wht/TriColor"},
    {"name": "Wht/Wht"},
    {"name": "Whte"},
    {"name": "Y BRINDLE"},
    {"name": "Y BRINDLE AND WHITE"},
    {"name": "Yello"},
    {"name": "Yellow"},
    {"name": "YELLOW AND BROWN"},
    {"name": "YELLOW AND GOLD"},
    {"name": "YELLOW AND TAN"},
    {"name": "Yellow and White"},
    {"name": "Yellow Collar"},
    {"name": "Yellow/Fawn"},
    {"name": "YellowandWhite"}
]


module.exports = DogColor;
